=head1 NAME

MediaWords::Crawler::Fetcher


=head1 DESCRIPTION

this is a simplified version of the code used crawler to interact with the fetcher


=head1 REQUIRES

L<MediaWords::Util::URL> 

L<MediaWords::Util::Web> 

L<MediaWords::Util::SQL> 

L<MediaWords::Util::Config> 

L<DBIx::Simple::MediaWords> 

L<MediaWords::DB> 

L<LWP::UserAgent> 

L<MediaWords::CommonLibs> 

L<Modern::Perl> 


=head1 METHODS

=head2 new

 $self->new();

=head2 do_fetch

 $self->do_fetch();

=head2 engine

 $self->engine();

=head2 fetch_download

 $self->fetch_download();


=cut

