version: "3.7"

services:

    rabbitmq-server-webapp-proxy:
        image: mc2021/rabbitmq-server-webapp-proxy:latest
        init: true
        stop_signal: SIGKILL
        ports:
            # Expose to host for debugging
            - "15672:15672"
        volumes:
            - type: bind
              source: ./nginx/include/
              target: /etc/nginx/include/
            - type: bind
              source: ./../nginx-base/nginx/nginx.conf
              target: /etc/nginx/nginx.conf
        depends_on:
            - rabbitmq-server

    rabbitmq-server:
        image: mc2021/rabbitmq-server:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672
        volumes:
            - type: bind
              source: ./../rabbitmq-server/conf/
              target: /etc/rabbitmq/
