brew 'coreutils'
brew 'cpanminus'
brew 'curl'
brew 'gawk'
brew 'tidy-html5'
brew 'hunspell'
brew 'libyaml'
brew 'logrotate'
brew 'netcat'
brew 'openssl'
brew 'perl'
brew 'python'
brew 'rabbitmq'
brew 'graphviz', args: ['with-bindings']