=head1 NAME

MediaWords::Util::DatabaseRestore


=head1 DESCRIPTION

misc utility functions for sql


=head1 REQUIRES

L<Time::Local> 

L<Try::Tiny> 

L<MediaWords::CommonLibs> 

L<Modern::Perl> 


=head1 METHODS

=head2 copy_data_until_line_num

 copy_data_until_line_num();

=head2 get_restore_table_name

 get_restore_table_name();

=head2 get_start_and_end_line_for_table

 get_start_and_end_line_for_table();

=head2 process_data_until_line_num

 process_data_until_line_num();

=head2 read_until_copy_statement

 read_until_copy_statement();

=head2 read_until_line_num

 read_until_line_num();

=head2 test_opening_files

 test_opening_files();

Tests opening the files to make sure they're valid



=cut

