=head1 NAME

MediaWords::Util::GearmanJobSchedulerConfiguration


=head1 DESCRIPTION


implements Gearman::JobScheduler::Configuration with values from Media Cloud's configuration



=head1 REQUIRES

L<MediaWords::Util::Config> 

L<MediaWords::CommonLibs> 

L<Modern::Perl> 

L<Gearman::JobScheduler::Configuration> 

L<Moose> 


=head1 METHODS

=head2 BUILD

 BUILD();


=cut

