#
# CLIFF update story tags worker
#

FROM dockermediacloud/mediacloud-cliff-base:latest

# Copy Python sources
COPY src/python/ /usr/lib/python3/dist-packages/

# FIXME
CMD ["bash", "-c", "while true; do echo cliff-update-story-tags...; sleep 1; done"]
