#
# Generate daily RSS dumps Cron job
#

FROM gcr.io/mcback/cron-base:latest

# Install Perl dependencies
COPY src/cpanfile /var/tmp/
RUN \
    cd /var/tmp/ && \
    cpm install --global --resolver 02packages --no-prebuilt --mirror "$MC_PERL_CPAN_MIRROR" && \
    rm cpanfile && \
    rm -rf /root/.perl-cpm/ && \
    true

# Copy Cron script
COPY bin /opt/mediacloud/bin

# Add Cron job
ADD crontab /etc/cron.d/generate_daily_rss_dumps
RUN chmod 0644 /etc/cron.d/generate_daily_rss_dumps

# Generated dumps
RUN \
    mkdir -p /var/lib/daily_rss_dumps/ && \
    #
    # "www-data" user / group is shared with "webapp-httpd" which will be
    # reading files generated by this app:
    chown www-data:www-data /var/lib/daily_rss_dumps/ && \
    #
    true

VOLUME /var/lib/daily_rss_dumps/

# CMD is set in "cron-base"
