=head1 NAME

MediaWords::Controller::Api::V2::MediaHealth


=head1 REQUIRES

L<Carp> 

L<namespace::autoclean> 

L<Moose> 

L<List::Util> 

L<JSON> 

L<MediaWords::CommonLibs> 

L<Modern::Perl> 


=head1 IMPLEMENTS

L<Catalyst::Controller> 


=head1 METHODS

=head2 has_nested_data

 $self->has_nested_data();

=head2 list_GET

 $self->list_GET();


=cut

