=head1 NAME

MediaWords::Controller::Api::V2::Media


=head1 DESCRIPTION

say STDERR "adding media_source tags ";


=head1 REQUIRES

L<MediaWords::CM::Dump> 

L<MediaWords::Solr> 

L<Carp> 

L<List::Compare> 

L<namespace::autoclean> 

L<Moose> 

L<List::Util> 

L<JSON> 

L<MediaWords::CommonLibs> 

L<Modern::Perl> 


=head1 IMPLEMENTS

L<Catalyst::Controller> 


=head1 METHODS

=head2 default_output_fields

 $self->default_output_fields();

=head2 get_extra_where_clause

 $self->get_extra_where_clause();

=head2 get_table_name

 $self->get_table_name();

=head2 has_nested_data

 $self->has_nested_data();

=head2 list_GET

 $self->list_GET();

=head2 list_name_search_field

 $self->list_name_search_field();

=head2 order_by_clause

 $self->order_by_clause();


=cut

