# states indicating the result of fetch_topic_url
FETCH_STATE_PENDING = 'pending'
FETCH_STATE_REQUEST_FAILED = 'request failed'
FETCH_STATE_CONTENT_MATCH_FAILED = 'content match failed'
FETCH_STATE_STORY_MATCH = 'story match'
FETCH_STATE_STORY_ADDED = 'story added'
FETCH_STATE_PYTHON_ERROR = 'python error'
FETCH_STATE_REQUEUED = 'requeued'
FETCH_STATE_KILLED = 'killed'
FETCH_STATE_IGNORED = 'ignored'
FETCH_STATE_SKIPPED = 'skipped'
FETCH_STATE_TWEET_PENDING = 'tweet pending'
FETCH_STATE_TWEET_ADDED = 'tweet added'
FETCH_STATE_TWEET_MISSING = 'tweet missing'
