=head1 NAME

MediaWords::DBI::DownloadTexts


=head1 DESCRIPTION

insert extracted lines into extracted_lines table


=head1 REQUIRES

L<Try::Tiny> 

L<MediaWords::DBI::Downloads> 

L<MediaWords::Util::HTML> 

L<MediaWords::Util::Config> 

L<Data::Dumper> 

L<Encode> 

L<MediaWords::CommonLibs> 

L<Modern::Perl> 


=head1 METHODS

=head2 create

 create();

=head2 get_extracted_html_from_db

 get_extracted_html_from_db();


=cut

