#
# Fetch story stats from Facebook
#

FROM dockermediacloud/mediacloud-common:latest

# Copy Perl sources
COPY src/perl/ /usr/share/perl5/

# FIXME
CMD ["bash", "-c", "while true; do echo facebook-fetch-story-stats...; sleep 1; done"]
