version: "3.7"

services:

    import-stories-scrapehtml:
        image: mc2021/import-stories-scrapehtml:latest
        init: true
        stop_signal: SIGKILL
        volumes:
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/import-stories-scrapehtml/
            - type: bind
              source: ./../import-stories-base/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../import-stories-base/src/
              target: /opt/mediacloud/src/import-stories-base/
            - type: bind
              source: ./../extract-and-vector/src/
              target: /opt/mediacloud/src/extract-and-vector/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - postgresql-pgbouncer

    postgresql-pgbouncer:
        image: mc2021/postgresql-pgbouncer:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 6432
        volumes:
            - type: bind
              source: ./../postgresql-pgbouncer/conf/
              target: /etc/pgbouncer/
        depends_on:
            - postgresql-server

    postgresql-server:
        image: mc2021/postgresql-server:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5432
        volumes:
            - type: bind
              source: ./../postgresql-server/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../postgresql-server/pgmigrate/
              target: /opt/postgresql-server/pgmigrate/
            - type: bind
              source: ./../postgresql-base/etc/postgresql/
              target: /etc/postgresql/
