=head1 NAME

MediaWords::DBI::Media::Lookup


=head1 DESCRIPTION

get matching all media that match the normalized url of the given medium


=head1 REQUIRES

L<MediaWords::Util::URL> 

L<MediaWords::DBI::Media> 

L<MediaWords::CommonLibs> 

L<Modern::Perl> 


=head1 METHODS

=head2 find_medium_by_url

 find_medium_by_url();

find the medium by looking for an existing medium with the same normalized url.
give prefernce first for non-spidered media and second for non-dup-media.



=cut

