# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

#
# AWS defaults
#

# AMI (see https://cloud-images.ubuntu.com/locator/ec2/)
AWS_AMI           = ENV['AWS_AMI']            || "ami-34cc7a5c"
AWS_REGION        = ENV['AWS_REGION']         || "us-east-1"
AWS_INSTANCE_NAME = ENV['AWS_INSTANCE_NAME']  || "Media Cloud Vagrant test box"

# "t1.tiny" is not enough to install and run Media Cloud because it doesn't
# have enough RAM available.
# "m3.medium" is just enough to install Media Cloud and run the full unit test
# suite. However, you might want to run Media Cloud on a bigger instance with
# more RAM if you are about to use Media Cloud in production environments.
AWS_INSTANCE_TYPE = ENV['AWS_AMI']            || "m3.medium"

#
# Main configuration
#
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #
  # on VirtualBox:
  #     vagrant up --provider=virtualbox
  #
  config.vm.provider :virtualbox do |vb|

    # Ubuntu 12.04 (64 bit)
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    # Access Media Cloud's 5000 port by opening localhost:5001
    config.vm.network :forwarded_port, guest: 5000, host: 5001

    # Access Media Cloud's 3000 port by opening localhost:3001
    config.vm.network :forwarded_port, guest: 3000, host: 3001

  end

  #
  # on AWS EC2:
  #     vagrant plugin install vagrant-aws
  #     vagrant up --provider=aws
  #
  config.vm.provider :aws do |aws, override|

    if ARGV.include? '--provider=aws'

      if ENV["AWS_ACCESS_KEY_ID"].nil? ||
         ENV["AWS_SECRET_ACCESS_KEY"].nil? ||
         ENV["AWS_KEYPAIR_NAME"].nil? ||
         ENV["AWS_SSH_PRIVKEY"].nil? ||
         ENV["AWS_SECURITY_GROUP"].nil?

        err_message = <<-eos
Set the following environment variables before continuing:

    export AWS_ACCESS_KEY_ID="AKIAIOSFODNN7EXAMPLE" # The API key used to make requests to AWS
    export AWS_SECRET_ACCESS_KEY="wJalrXUtnFEMI/K7MDENG" # The secret key to make AWS API requests
    export AWS_KEYPAIR_NAME="development" # The name of the keypair used for this EC2 instance
    export AWS_SSH_PRIVKEY="~/development.pem" # The path to the private key for the named keypair
    export AWS_SECURITY_GROUP="default" # Security group to assign to this EC2 instance

See doc/README.vagrant.markdown for instructions on how to set those variables.
        eos

        abort(err_message)

      end
    end

    override.vm.box = "ubuntu_aws"
    override.vm.box_url = "aws_ec2_dummy.box"

    # default username of Ubuntu ABIs
    override.ssh.username = "ubuntu"

    aws.access_key_id = ENV["AWS_ACCESS_KEY_ID"]
    aws.secret_access_key = ENV["AWS_SECRET_ACCESS_KEY"]

    aws.keypair_name = ENV["AWS_KEYPAIR_NAME"]
    override.ssh.private_key_path = ENV["AWS_SSH_PRIVKEY"]

    aws.region = AWS_REGION
    aws.ami    = AWS_AMI
    aws.instance_type = AWS_INSTANCE_TYPE
    aws.tags = { 'Name' => AWS_INSTANCE_NAME }

    # Media Cloud barely fits into instance's default 8 GB
    aws.block_device_mapping = [{
      'DeviceName' => '/dev/sda1',
      'Ebs.VolumeSize' => 40
    }]

    # Wait for more than the default (120 seconds) for the instance to start
    aws.instance_ready_timeout = 360

    aws.security_groups = [ ENV["AWS_SECURITY_GROUP"] ]

  end

  # Hostname
  config.vm.hostname = "mediacloud.local"

  # Share Media Cloud's repository as /mediacloud
  # (path is relative to ./script/vagrant)
  # Will mount on VirtualBox, rsync on AWS EC2
  config.vm.synced_folder "../../", "/mediacloud"

  # Provision scripts
  config.vm.provision "shell", privileged: true, path: "provision_root.sh"
  config.vm.provision "shell", privileged: false, path: "provision_user.sh"

end
