global:
  scrape_interval: 15s
  scrape_timeout: 30s

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:

  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
    - targets:
      - 'localhost:9090'

  - job_name: 'services'
    static_configs:
    - targets:
      # frontend
      - 'temporal-server:9091'
      # matching
      - 'temporal-server:9092'
      # history
      - 'temporal-server:9093'
      # worker
      - 'temporal-server:9094'

  # rabbitmq monitoring from rabbitmq_prometheus plugin
  - job_name: 'rabbitmq'
    metrics_path: /metrics
    static_configs:
      - targets:
          - "rabbitmq-server:15692"

