=head1 NAME

MediaWords::GearmanFunction::Bitly::EnqueueAllControversyStories


=head1 DESCRIPTION


Enqueue all controversy's stories for processing via Bit.ly API

Start this worker script by running:

./script/run_with_carton.sh local/bin/gjs_worker.pl lib/MediaWords/GearmanFunction/Bitly/EnqueueAllControversyStories.pm



=head1 REQUIRES

L<Readonly> 

L<MediaWords::GearmanFunction::Bitly::FetchStoryStats> 

L<MediaWords::Util::DateTime> 

L<MediaWords::Util::Bitly> 

L<MediaWords::Util::GearmanJobSchedulerConfiguration> 

L<MediaWords::DB> 

L<MediaWords::CommonLibs> 

L<Modern::Perl> 

L<lib> 

L<FindBin> 

L<Moose> 


=head1 METHODS

=head2 configuration()

 configuration()();

(Gearman::JobScheduler::AbstractFunction implementation) Return default configuration


=head2 run($;$)

 run($;$)();

Run job


=head2 unify_logs()

 unify_logs()();

write a single log because there are a lot of Bit.ly processing jobs so it's
impractical to log each job into a separate file



=cut

