=head1 NAME

MediaWords::ActionRole::Logged


=head1 DESCRIPTION


Action role that logs requests



=head1 REQUIRES

L<Readonly> 

L<HTTP::Status> 

L<namespace::autoclean> 

L<Moose::Role> 

L<MediaWords::CommonLibs> 

L<Modern::Perl> 


=head1 METHODS

=head2 set_requested_items_count($$)

 set_requested_items_count($$)();

Static helper that sets the number of requested items (e.g. stories) in the Catalyst's stash to be later used by after{}



=cut

