=head1 NAME

MediaWords::KeyValueStore::MultipleStores


=head1 DESCRIPTION

handler for multiple key-value stores


=head1 REQUIRES

L<Carp> 

L<MediaWords::CommonLibs> 

L<Modern::Perl> 

L<Moose> 


=head1 METHODS

=head2 BUILD($$)

 BUILD($$)();

=head2 content_exists($$$$)

 content_exists($$$$)();

Test if content exists in at least one of the stores
die() if at least one of the stores failed testing for content


=head2 fetch_content($$$$)

 fetch_content($$$$)();

Fetch content from any of the stores that might have it
die() if none of the stores have it


=head2 remove_content($$$$)

 remove_content($$$$)();

Remove content from all of the stores
die() if removal from at least one of the stores failed


=head2 store_content($$$$)

 store_content($$$$)();

Store content in all of the stores
die() if storing in one of the stores failed



=cut

