--
-- This is a Media Cloud PostgreSQL schema difference file (a "diff") between schema
-- versions 4620 and 4621.
--
-- If you are running Media Cloud with a database that was set up with a schema version
-- 4620, and you would like to upgrade both the Media Cloud and the
-- database to be at version 4621, import this SQL file:
--
--     psql mediacloud < mediawords-4620-4621.sql
--
-- You might need to import some additional schema diff files to reach the desired version.
--

--
-- 1 of 2. Import the output of 'apgdiff':
--

SET search_path = public, pg_catalog;

DROP INDEX auth_user_ip_address_api_keys_api_key_ip_address;
DROP INDEX auth_users_api_key;

ALTER TABLE auth_user_ip_address_api_keys
    RENAME TO auth_user_api_keys;

ALTER TABLE auth_user_api_keys
    ALTER COLUMN ip_address DROP NOT NULL;

-- Copy existing non-IP limited API keys to "auth_user_api_keys"
INSERT INTO auth_user_api_keys (auth_users_id, api_key, ip_address)
    SELECT auth_users_id, api_key, NULL
    FROM auth_users;

ALTER TABLE auth_users
	DROP COLUMN api_key;

CREATE UNIQUE INDEX auth_user_api_keys_api_key_ip_address
    ON auth_user_api_keys (api_key, ip_address);

-- Autogenerate non-IP limited API key
CREATE OR REPLACE FUNCTION auth_user_api_keys_add_non_ip_limited_api_key() RETURNS trigger AS
$$
BEGIN

    INSERT INTO auth_user_api_keys (auth_users_id, api_key, ip_address)
    VALUES (
        NEW.auth_users_id,
        DEFAULT,  -- Autogenerated API key
        NULL      -- Not limited by IP address
    );
    RETURN NULL;

END;
$$
LANGUAGE 'plpgsql';

CREATE TRIGGER auth_user_api_keys_add_non_ip_limited_api_key
    AFTER INSERT ON auth_users
    FOR EACH ROW EXECUTE PROCEDURE auth_user_api_keys_add_non_ip_limited_api_key();


CREATE OR REPLACE FUNCTION set_database_schema_version() RETURNS boolean AS $$
DECLARE

    -- Database schema version number (same as a SVN revision number)
    -- Increase it by 1 if you make major database schema changes.
    MEDIACLOUD_DATABASE_SCHEMA_VERSION CONSTANT INT := 4621;

BEGIN

    -- Update / set database schema version
    DELETE FROM database_variables WHERE name = 'database-schema-version';
    INSERT INTO database_variables (name, value) VALUES ('database-schema-version', MEDIACLOUD_DATABASE_SCHEMA_VERSION::int);

    return true;

END;
$$
LANGUAGE 'plpgsql';

--
-- 2 of 2. Reset the database version.
--
SELECT set_database_schema_version();
