#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
require 5.6.0;
use strict;
use warnings;
use Thrift;

use thrift_solr::Types;

# HELPER FUNCTIONS AND STRUCTURES

package thrift_solr::ExtractorService_extract_html_args;
use base qw(Class::Accessor);
thrift_solr::ExtractorService_extract_html_args->mk_accessors( qw( raw_html ) );

sub new {
    my $classname = shift;
    my $self      = {};
    my $vals      = shift || {};
    $self->{raw_html} = undef;
    if (UNIVERSAL::isa($vals,'HASH')) {
      if (defined $vals->{raw_html}) {
        $self->{raw_html} = $vals->{raw_html};
      }
    }
    return bless ($self, $classname);
}

sub getName {
    return 'ExtractorService_extract_html_args';
  }

sub read {
    my ($self, $input) = @_;
    my $xfer  = 0;
    my $fname;
    my $ftype = 0;
    my $fid   = 0;
    $xfer += $input->readStructBegin(\$fname);
    while (1) 
    {
      $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
      if ($ftype == TType::STOP) {
        last;
      }
      SWITCH: for($fid)
      {
        /^1$/ && do{        if ($ftype == TType::STRING) {
          $xfer += $input->readString(\$self->{raw_html});
        } else {
          $xfer += $input->skip($ftype);
        }
        last; };
          $xfer += $input->skip($ftype);
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

sub write {
    my ($self, $output) = @_;
    my $xfer   = 0;
    $xfer += $output->writeStructBegin('ExtractorService_extract_html_args');
    if (defined $self->{raw_html}) {
      $xfer += $output->writeFieldBegin('raw_html', TType::STRING, 1);
      $xfer += $output->writeString($self->{raw_html});
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

package thrift_solr::ExtractorService_extract_html_result;
use base qw(Class::Accessor);
thrift_solr::ExtractorService_extract_html_result->mk_accessors( qw( success ) );

sub new {
    my $classname = shift;
    my $self      = {};
    my $vals      = shift || {};
    $self->{success} = undef;
    if (UNIVERSAL::isa($vals,'HASH')) {
      if (defined $vals->{success}) {
        $self->{success} = $vals->{success};
      }
    }
    return bless ($self, $classname);
}

sub getName {
    return 'ExtractorService_extract_html_result';
  }

sub read {
    my ($self, $input) = @_;
    my $xfer  = 0;
    my $fname;
    my $ftype = 0;
    my $fid   = 0;
    $xfer += $input->readStructBegin(\$fname);
    while (1) 
    {
      $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
      if ($ftype == TType::STOP) {
        last;
      }
      SWITCH: for($fid)
      {
        /^0$/ && do{        if ($ftype == TType::LIST) {
          {
            my $_size16 = 0;
            $self->{success} = [];
            my $_etype19 = 0;
            $xfer += $input->readListBegin(\$_etype19, \$_size16);
            for (my $_i20 = 0; $_i20 < $_size16; ++$_i20)
            {
              my $elem21 = undef;
              $xfer += $input->readString(\$elem21);
              push(@{$self->{success}},$elem21);
            }
            $xfer += $input->readListEnd();
          }
        } else {
          $xfer += $input->skip($ftype);
        }
        last; };
          $xfer += $input->skip($ftype);
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

sub write {
    my ($self, $output) = @_;
    my $xfer   = 0;
    $xfer += $output->writeStructBegin('ExtractorService_extract_html_result');
    if (defined $self->{success}) {
      $xfer += $output->writeFieldBegin('success', TType::LIST, 0);
      {
        $xfer += $output->writeListBegin(TType::STRING, scalar(@{$self->{success}}));
        {
          foreach my $iter22 (@{$self->{success}}) 
          {
            $xfer += $output->writeString($iter22);
          }
        }
        $xfer += $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

package thrift_solr::ExtractorServiceIf;

use strict;


sub extract_html{
  my $self = shift;
  my $raw_html = shift;

  die 'implement interface';
}

package thrift_solr::ExtractorServiceRest;

use strict;


sub new {
    my ($classname, $impl) = @_;
    my $self     ={ impl => $impl };

    return bless($self,$classname);
}

sub extract_html{
    my ($self, $request) = @_;

    my $raw_html = ($request->{'raw_html'}) ? $request->{'raw_html'} : undef;
    return $self->{impl}->extract_html($raw_html);
  }

package thrift_solr::ExtractorServiceClient;


use base qw(thrift_solr::ExtractorServiceIf);
sub new {
    my ($classname, $input, $output) = @_;
    my $self      = {};
    $self->{input}  = $input;
    $self->{output} = defined $output ? $output : $input;
    $self->{seqid}  = 0;
    return bless($self,$classname);
}

sub extract_html{
  my $self = shift;
  my $raw_html = shift;

        $self->send_extract_html($raw_html);
    return $self->recv_extract_html();
}

sub send_extract_html{
  my $self = shift;
  my $raw_html = shift;

    $self->{output}->writeMessageBegin('extract_html', TMessageType::CALL, $self->{seqid});
    my $args = new thrift_solr::ExtractorService_extract_html_args();
    $args->{raw_html} = $raw_html;
    $args->write($self->{output});
    $self->{output}->writeMessageEnd();
    $self->{output}->getTransport()->flush();
}

sub recv_extract_html{
  my $self = shift;

    my $rseqid = 0;
    my $fname;
    my $mtype = 0;

    $self->{input}->readMessageBegin(\$fname, \$mtype, \$rseqid);
    if ($mtype == TMessageType::EXCEPTION) {
      my $x = new TApplicationException();
      $x->read($self->{input});
      $self->{input}->readMessageEnd();
      die $x;
    }
    my $result = new thrift_solr::ExtractorService_extract_html_result();
    $result->read($self->{input});
    $self->{input}->readMessageEnd();

    if (defined $result->{success} ) {
      return $result->{success};
    }
    die "extract_html failed: unknown result";
}
package thrift_solr::ExtractorServiceProcessor;

use strict;


sub new {
      my ($classname, $handler) = @_;
      my $self      = {};
      $self->{handler} = $handler;
      return bless ($self, $classname);
}

sub process {
      my ($self, $input, $output) = @_;
      my $rseqid = 0;
      my $fname  = undef;
      my $mtype  = 0;

      $input->readMessageBegin(\$fname, \$mtype, \$rseqid);
      my $methodname = 'process_'.$fname;
      if (!$self->can($methodname)) {
        $input->skip(TType::STRUCT);
        $input->readMessageEnd();
        my $x = new TApplicationException('Function '.$fname.' not implemented.', TApplicationException::UNKNOWN_METHOD);
        $output->writeMessageBegin($fname, TMessageType::EXCEPTION, $rseqid);
        $x->write($output);
        $output->writeMessageEnd();
        $output->getTransport()->flush();
        return;
      }
      $self->$methodname($rseqid, $input, $output);
      return 1;
}

sub process_extract_html {
      my ($self, $seqid, $input, $output) = @_;
      my $args = new thrift_solr::ExtractorService_extract_html_args();
      $args->read($input);
      $input->readMessageEnd();
      my $result = new thrift_solr::ExtractorService_extract_html_result();
      $result->{success} = $self->{handler}->extract_html($args->raw_html);
      $output->writeMessageBegin('extract_html', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
}

1;
