#
# 1. Copy this file to global-env.inc.sh
# 2. Update the environment variables
# 3. Load environment variables to your host machine's shell:
#
#     source global-env.inc.sh
#
# 4. Deploy the stack:
#
#    docker stack deploy -c docker-compose.yml mediacloud
#

export MC_DOWNLOADS_AMAZON_S3_ACCESS_KEY_ID="CHANGEME"
export MC_DOWNLOADS_AMAZON_S3_SECRET_ACCESS_KEY="CHANGEME"
export MC_DOWNLOADS_AMAZON_S3_BUCKET_NAME="CHANGEME"
export MC_DOWNLOADS_AMAZON_S3_DIRECTORY_NAME="CHANGEME"
export MC_EMAIL_FROM_ADDRESS="CHANGEME"
export MC_USERAGENT_AUTHENTICATED_DOMAINS="CHANGEME"
export MC_TOPICS_BASE_TOPIC_ALERT_EMAILS="CHANGEME"
export MC_CLIFF_ANNOTATOR_URL="CHANGEME"
export MC_FACEBOOK_APP_ID="CHANGEME"
export MC_FACEBOOK_APP_SECRET="CHANGEME"
export MC_PROXY_CERTBOT_CLOUDFLARE_EMAIL="CHANGEME"
export MC_PROXY_CERTBOT_CLOUDFLARE_GLOBAL_API_KEY="CHANGEME"
export MC_TWITTER_CONSUMER_KEY="CHANGEME"
export MC_TWITTER_CONSUMER_SECRET="CHANGEME"
export MC_TWITTER_ACCESS_TOKEN="CHANGEME"
export MC_TWITTER_ACCESS_TOKEN_SECRET="CHANGEME"
export MC_CRIMSON_HEXAGON_API_KEY="CHANGEME"
