version: "3.7"

services:

    cron-refresh-stats:
        image: gcr.io/mcback/cron-refresh-stats:latest
        init: true
        stop_signal: SIGKILL
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../cron-base/bin/cron.sh
              target: /cron.sh
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - postgresql-pgbouncer

    postgresql-pgbouncer:
        image: gcr.io/mcback/postgresql-pgbouncer:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 6432
        volumes:
            - type: bind
              source: ./../postgresql-pgbouncer/conf/
              target: /etc/pgbouncer/
        depends_on:
            - postgresql-server

    postgresql-server:
        image: gcr.io/mcback/postgresql-server:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5432
        volumes:
            - type: bind
              source: ./../postgresql-server/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../postgresql-server/pgmigrate/
              target: /opt/postgresql-server/pgmigrate/
            - type: bind
              source: ./../postgresql-server/etc/postgresql/14/extra/
              target: /etc/postgresql/14/extra/
            - type: bind
              source: ./../postgresql-base/etc/postgresql/14/main/
              target: /etc/postgresql/14/main/
