#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib $FindBin::Bin;

use MediaWords::Munin;

MediaWords::Munin::plugin({
    title => 'Downloads in last day',
    info => 'Downloads in the last day',
    vlabel => 'Downloads',
    metrics => [
        {
            label => 'Downloads',
            color => $COLOR1,
            warning => { from => 250_000 },
            critical => { from => 100_000 },
            value => sub {
                
                my $db = shift;

                my $download_count = $db->query(<<SQL
                    SELECT (max_downloads_id - downloads_id_from_last_day) AS downloads_in_past_day
                    FROM (
                        SELECT downloads_id AS downloads_id_from_last_day
                        FROM downloads
                        WHERE download_time >= NOW() - '1 day'::interval
                        ORDER BY download_time
                        LIMIT 1
                    ) AS d1,
                    (
                        SELECT MAX(downloads_id) AS max_downloads_id
                        FROM downloads
                    ) AS d2
SQL
                )->flat->[0];

                unless ( defined $download_count ) {
                    print STDERR "No downloads since yesterday.\n";
                    return 0;
                }

                return $download_count;
            },
        },
    ],
});
