#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib $FindBin::Bin;

use MediaWords::Munin;

MediaWords::Munin::plugin({
    title => 'Unextracted downloads',
    info => "Downloads with extracted = \'f\' and state = \'success\' and type = \'content\'",
    vlabel => 'Downloads',
    metrics => [
        {
            label => 'Downloads',
            color => $COLOR10,
            value => sub {
                my $db = shift;
                return $db->query(<<SQL
                    SELECT COUNT(1)
                    FROM downloads
                    WHERE extracted = 'f'
                      AND state = 'success'
                      AND type = 'content'
SQL
                )->flat->[0];
            },
        }
    ],
});
