#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib $FindBin::Bin;

use MediaWords::Munin;

MediaWords::Munin::plugin({
    title => 'Solr imports in last day',
    info => 'Solr imports in the last day, as reported by "solr_imports" table',
    vlabel => 'Count',
    metrics => [
        {
            label => 'Solr imports',
            color => $COLOR1,
            warning => { from => 22 },
            critical => { from => 20 },
            value => sub {
                my $db = shift;
                return $db->query(<<SQL
                    SELECT COUNT(1)
                    FROM solr_imports
                    WHERE import_date > NOW() - '1 day'::interval
SQL
                )->flat->[0];
            },
        },
    ],
});
