#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib $FindBin::Bin;

use MediaWords::Munin;
use JSON;
use URI;
use LWP::Simple qw($ua get);

MediaWords::Munin::plugin({
    title => 'Solr import stories',
    info => 'Number of rows in solr_import_stories',
    vlabel => 'Count',
    metrics => [
        {
            label => 'Solr import stories',
            color => $COLOR2,
            warning => { from => 0, to => 50_000_000 },
            critical => { from => 0, to => 200_000_000 },
            value => sub {
                my $db = shift;

                my ( $count ) = $db->query( <<SQL )->flat();
select ((reltuples/relpages) *
			(pg_relation_size('solr_import_stories') / (current_setting('block_size')::integer))
		)::bigint
	from pg_class where relname = 'solr_import_stories'
SQL

                return $count;
            },
        },
    ],
});
