requires 'Carp::Always';
requires 'CHI';
requires 'Fcntl';
requires 'HTML::LinkExtractor';
requires 'Parallel::ForkManager';
requires 'Parse::BooleanLogic';
requires 'Perl::Tidy';
requires 'Term::Prompt';
requires 'Term::ReadKey';

